"""Persistence contract for authored skills, nouns, verbs, and bindings."""

from __future__ import annotations

from typing import Protocol

from boltrig.models import Noun, Skill, Verb, VerbBinding


class AuthoredDefinitionStoreContract(Protocol):
    """Active runtime reads plus unfiltered governance/cleanup reads."""

    async def get_noun(self, tenant_id: str, noun_id: str) -> Noun | None: ...
    async def get_noun_any(self, tenant_id: str, noun_id: str) -> Noun | None: ...
    async def list_nouns(self, tenant_id: str) -> list[Noun]: ...
    async def list_all_nouns(self, tenant_id: str) -> list[Noun]: ...
    async def get_verb(self, tenant_id: str, verb_id: str) -> Verb | None: ...
    async def get_verb_any(self, tenant_id: str, verb_id: str) -> Verb | None: ...
    async def list_verbs(
        self, tenant_id: str, noun_id: str | None = None
    ) -> list[Verb]: ...
    async def list_all_verbs(
        self, tenant_id: str, noun_id: str | None = None
    ) -> list[Verb]: ...
    async def get_binding(
        self, tenant_id: str, verb_id: str
    ) -> VerbBinding | None: ...
    async def upsert_noun(self, noun: Noun) -> None: ...
    async def upsert_verb(self, verb: Verb) -> None: ...
    async def set_noun_active(
        self, tenant_id: str, noun_id: str, active: bool
    ) -> Noun | None: ...
    async def set_verb_active(
        self, tenant_id: str, verb_id: str, active: bool
    ) -> Verb | None: ...
    async def upsert_binding(self, binding: VerbBinding) -> None: ...
    async def delete_noun(self, tenant_id: str, noun_id: str) -> None: ...
    async def delete_verb(self, tenant_id: str, verb_id: str) -> None: ...
    async def delete_binding(self, tenant_id: str, verb_id: str) -> None: ...

    async def upsert_skill(self, skill: Skill) -> None: ...
    async def get_skill(self, tenant_id: str, skill_id: str) -> Skill | None: ...
    async def get_skill_any(
        self, tenant_id: str, skill_id: str
    ) -> Skill | None: ...
    async def list_skills(self, tenant_id: str) -> list[Skill]: ...
    async def list_all_skills(self, tenant_id: str) -> list[Skill]: ...
    async def set_skill_active(
        self, tenant_id: str, skill_id: str, active: bool
    ) -> Skill | None: ...
