"""The Store protocol - the kernel's only persistence seam.

The kernel depends on this Protocol, never on a concrete DB. ``InMemoryStore``
satisfies it for dev/tests; a Postgres-backed store (schema in ``schema.sql``)
satisfies the same Protocol for production. Tenant isolation (SEC-08) is a
contract of every method: an id lookup is always scoped by ``tenant_id``.
"""

from __future__ import annotations

from datetime import datetime
from typing import Protocol, runtime_checkable

from boltrig.models import (
    AdapterRecord,
    AgentCapability,
    AuditEvent,
    Budget,
    Channel,
    ChannelBinding,
    ChannelPairing,
    ConfigRevision,
    Conversation,
    ConversationMessage,
    EvalCase,
    EvalRun,
    HITLRequest,
    MemoryErasure,
    MemoryFact,
    MemoryIngestion,
    MemoryItem,
    NotificationPref,
    PersonalAccessToken,
    PersonalAgent,
    HITLResponse,
    ModelEndpoint,
    Noun,
    Skill,
    TenantPermissions,
    User,
    UserInvitation,
    UserSession,
    UserSetting,
    Verb,
    VerbBinding,
    WorkflowDefinition,
    WorkItem,
    WorkStatus,
)
from boltrig.models.work import RunCheckpoint

# --- resource-bounding ceilings (M7 / M9 DoS-bounding, SEC-69) --------------
# A list read must never be able to return an unbounded slice: an ever-growing
# tenant table would otherwise let one caller exhaust memory/latency. The store
# clamps every explicit page to MAX_WORK_PAGE; the HTTP surface asks for
# DEFAULT_WORK_PAGE by default. limit=None on the store keeps the legacy
# full-slice contract for internal callers (e.g. the own-data export) that must
# see every row, and is never reachable from the /v1/work HTTP surface.
MAX_WORK_PAGE = 500
DEFAULT_WORK_PAGE = 100
# The structured-memory list reads (M9-memory / SEC-009): the caller may ask for
# a page size but the server caps it, and a batch ingest is capped by item count.
MAX_MEMORY_LIST = 200
MAX_INGEST_ITEMS = 100


def clamp_work_page(limit: int) -> int:
    """Clamp a caller-supplied work-list page size into [1, MAX_WORK_PAGE]."""
    return max(1, min(int(limit), MAX_WORK_PAGE))


def clamp_memory_list(limit: int) -> int:
    """Clamp a caller-supplied memory-list page size into [1, MAX_MEMORY_LIST]."""
    return max(1, min(int(limit), MAX_MEMORY_LIST))


@runtime_checkable
class Store(Protocol):
    # --- registry ---
    async def get_noun(self, tenant_id: str, noun_id: str) -> Noun | None: ...
    async def get_verb(self, tenant_id: str, verb_id: str) -> Verb | None: ...
    async def list_verbs(self, tenant_id: str, noun_id: str | None = None) -> list[Verb]: ...
    async def get_binding(self, tenant_id: str, verb_id: str) -> VerbBinding | None: ...
    async def upsert_noun(self, noun: Noun) -> None: ...
    async def upsert_verb(self, verb: Verb) -> None: ...
    async def upsert_binding(self, binding: VerbBinding) -> None: ...

    # --- permissions ---
    async def get_tenant_permissions(self, tenant_id: str) -> TenantPermissions: ...

    # --- libraries ---
    async def upsert_adapter(self, adapter: AdapterRecord) -> None: ...
    async def get_adapter(self, tenant_id: str, adapter_id: str) -> AdapterRecord | None: ...
    async def list_adapters(self, tenant_id: str) -> list[AdapterRecord]: ...
    async def upsert_skill(self, skill: Skill) -> None: ...
    async def get_skill(self, tenant_id: str, skill_id: str) -> Skill | None: ...
    async def list_skills(self, tenant_id: str) -> list[Skill]: ...
    async def upsert_capability(self, cap: AgentCapability) -> None: ...
    async def list_capabilities(self, tenant_id: str) -> list[AgentCapability]: ...
    async def upsert_workflow(self, wf: WorkflowDefinition) -> None: ...
    async def list_workflows(self, tenant_id: str) -> list[WorkflowDefinition]: ...
    async def upsert_model_endpoint(self, ep: ModelEndpoint) -> None: ...
    async def get_model_endpoint(self, tenant_id: str, ep_id: str) -> ModelEndpoint | None: ...

    # --- work items ---
    async def create_work_item(self, item: WorkItem) -> None: ...
    async def get_work_item(self, tenant_id: str, item_id: str) -> WorkItem | None: ...
    async def update_work_item(self, item: WorkItem) -> None: ...
    async def list_work_items(
        self,
        tenant_id: str,
        status: WorkStatus | None = None,
        parent_id: str | None = None,
        departments: list[str] | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> list[WorkItem]:
        # M7 / SEC-69 DoS-bounding: an explicit ``limit`` (server-clamped to
        # MAX_WORK_PAGE) plus a keyset ``cursor`` on the row id bounds the page.
        # id is the table's stable PRIMARY KEY (tenant_id, id) and rides on every
        # returned row, so the next cursor is simply the last item's id - no
        # created_at is carried on the WorkItem, so an id keyset (not (created_at,
        # id)) is the stable, overlap-free scheme. ``limit=None`` = full slice
        # (legacy internal callers only). The tenant + status + department filters
        # are unchanged. Rows come back ordered by id so paging never overlaps.
        ...
    # atomic pending -> in_flight claim with a lease: one winner per item across
    # concurrent claimers; an expired lease is reclaimable; attempts increments
    # per claim (US-FLT-05). Mirrors the consume_hitl CAS shape.
    async def claim_work_item(
        self, tenant_id: str, worker_id: str, lease_seconds: int
    ) -> WorkItem | None: ...
    # atomic capped fan-out counter shared across workers (US-EXE-07): True and
    # the whole increment applied when value + n <= cap, False (nothing applied)
    # otherwise.
    async def try_increment_fanout(
        self, tenant_id: str, tree_id: str, counter: str, n: int, cap: int
    ) -> bool: ...
    # durable per-step run checkpoints - the resume seam for the pump (Beat 4).
    async def upsert_checkpoint(
        self,
        tenant_id: str,
        run_id: str,
        step: str,
        status: str,
        output: dict | None = None,
        hitl_request_id: str | None = None,
    ) -> None: ...
    async def list_checkpoints(self, tenant_id: str, run_id: str) -> list[RunCheckpoint]: ...

    # --- server-side run cancellation ([2026] VJS-COUNTY 6) ------------------
    # A cooperative, owner-only cancel signal keyed by run id. The route writes
    # the request THROUGH this narrow seam (owner-only + audited at the route,
    # mirroring rename/regenerate); the pump consults ``is_run_cancel_requested``
    # at each step boundary and stops BEFORE dispatching the next verb, never
    # interrupting an in-flight adapter call (D2/D3). A marker row, NOT a broad
    # mutable run table; idempotent (a re-request is a no-op, the first requester
    # stands). Durable: a restart re-detects the request and re-writes the
    # terminal CANCELLED state, so a cancelled run is never resurrected. Tenant-
    # scoped (SEC-08).
    async def request_run_cancel(
        self, tenant_id: str, run_id: str, requested_by: str
    ) -> None: ...
    async def is_run_cancel_requested(self, tenant_id: str, run_id: str) -> bool: ...

    # --- hitl ---
    async def create_hitl_request(self, req: HITLRequest) -> None: ...
    async def get_hitl_request(self, tenant_id: str, req_id: str) -> HITLRequest | None: ...
    async def list_pending_hitl(self, tenant_id: str) -> list[HITLRequest]: ...
    async def answer_hitl(self, resp: HITLResponse) -> HITLRequest | None: ...
    async def get_hitl_response(
        self, tenant_id: str, request_id: str
    ) -> HITLResponse | None: ...
    # atomic ANSWERED -> CONSUMED; True only for the caller that won the CAS (SEC-14).
    async def consume_hitl(self, tenant_id: str, request_id: str) -> bool: ...

    # --- audit (hash chain head + append + query) ---
    async def audit_head(self, tenant_id: str) -> tuple[int, str | None]: ...
    async def audit_append(self, event: AuditEvent) -> None: ...
    async def audit_query(
        self, tenant_id: str, run_id: str | None = None, limit: int = 200
    ) -> list[AuditEvent]: ...

    # --- budgets ---
    async def get_budget(self, tenant_id: str, scope_id: str) -> Budget | None: ...
    async def list_budgets(self, tenant_id: str) -> list[Budget]: ...
    async def consume_budget(
        self, tenant_id: str, scope_id: str, tokens: int, micros: int
    ) -> bool: ...
    # Post-run cost true-up (FR-COST-03, audit M14): apply a SIGNED delta to the
    # scope's accumulators atomically (FOR UPDATE in postgres, under the lock in
    # memory), each floored at 0. Unlike consume_budget this never gates on the
    # hard stop - it corrects the ledger for a call that already ran. A scope with
    # no budget row is a no-op (unmetered), mirroring consume_budget.
    async def reconcile_budget(
        self, tenant_id: str, scope_id: str, delta_tokens: int, delta_micros: int
    ) -> None: ...
    # Transactional multi-scope reserve (audit H4, engine-plan Phase 6, FR-COST-05):
    # debit EVERY scope in ``reservations`` (each a (scope_id, tokens, micros)
    # triple) in ONE all-or-nothing step. Either every hard-stop scope has headroom
    # and all are debited (returns True), or the first hard-stop scope with no
    # headroom aborts the whole thing and NONE is debited (returns False). Postgres
    # locks every scope's row FOR UPDATE in a deterministic order (sorted by
    # scope_id, so concurrent reserves on overlapping scopes cannot deadlock) and
    # re-checks each hard stop under the lock; memory applies the same semantics
    # under its no-await lock. A scope with no budget row is a no-op (unmetered),
    # mirroring consume_budget. This closes the partial-debit window the old
    # per-scope consume_budget loop left open: scope A debited, scope B refuses,
    # A stays charged for a call that never ran.
    async def reserve_budgets_atomic(
        self, tenant_id: str, reservations: list[tuple[str, int, int]]
    ) -> bool: ...

    # --- idempotency (SEC-15) ---
    async def idempotency_get(self, tenant_id: str, key: str) -> dict | None: ...
    async def idempotency_put(self, tenant_id: str, key: str, result: dict) -> None: ...

    # --- credential references (refs only; never plaintext, SEC-04) ---
    async def get_credential_ref(self, tenant_id: str, cred_id: str) -> dict | None: ...

    # --- Round Three: versioned config, eval, customisation, memory ---
    async def add_config_revision(self, rev: ConfigRevision) -> ConfigRevision: ...
    async def list_config_revisions(
        self, tenant_id: str, kind: str, ref: str
    ) -> list[ConfigRevision]: ...
    async def get_config_revision(self, tenant_id: str, rev_id: int) -> ConfigRevision | None: ...
    async def upsert_eval_case(self, case: EvalCase) -> None: ...
    async def get_eval_case(self, tenant_id: str, case_id: str) -> EvalCase | None: ...
    async def list_eval_cases(self, tenant_id: str) -> list[EvalCase]: ...
    async def add_eval_run(self, run: EvalRun) -> None: ...
    async def list_eval_runs(
        self, tenant_id: str, case_id: str | None = None
    ) -> list[EvalRun]: ...
    async def upsert_notification_pref(self, pref: NotificationPref) -> None: ...
    async def list_notification_prefs(self, tenant_id: str) -> list[NotificationPref]: ...
    async def upsert_personal_agent(self, agent: PersonalAgent) -> None: ...
    async def get_personal_agent(self, tenant_id: str, user_id: str) -> PersonalAgent | None: ...

    # --- Channels (Channels feature, decision 0003) --------------------------
    async def upsert_channel(self, channel: "Channel") -> None: ...
    async def get_channel(self, tenant_id: str, channel_id: str) -> "Channel | None": ...
    # Cross-tenant lookup by the unguessable channel id: the inbound path resolves
    # the tenant from the channel BEFORE any tenant is bound (like get_pat_by_hash).
    async def get_channel_by_id(self, channel_id: str) -> "Channel | None": ...
    async def list_channels(self, tenant_id: str) -> list["Channel"]: ...
    async def delete_channel(self, tenant_id: str, channel_id: str) -> None: ...
    async def upsert_channel_binding(self, binding: "ChannelBinding") -> None: ...
    async def get_channel_binding(
        self, tenant_id: str, channel_id: str, external_user_id: str
    ) -> "ChannelBinding | None": ...
    async def list_channel_bindings(
        self, tenant_id: str, channel_id: str
    ) -> list["ChannelBinding"]: ...
    async def delete_channel_binding(self, tenant_id: str, binding_id: str) -> None: ...
    async def create_channel_pairing(self, pairing: "ChannelPairing") -> None: ...
    async def get_channel_pairing_by_code(
        self, tenant_id: str, channel_id: str, code_hash: str
    ) -> "ChannelPairing | None": ...
    # Atomic pending -> consumed CAS (single-use pairing, mirrors consume_hitl).
    async def consume_channel_pairing(self, tenant_id: str, pairing_id: str) -> bool: ...
    # The pending pairing for a sender (for wrong-code lockout; the lookup is by
    # sender, not code, so a bad code still finds the row to increment attempts).
    async def get_pending_pairing_for_sender(
        self, tenant_id: str, channel_id: str, external_user_id: str
    ) -> "ChannelPairing | None": ...
    # Increment attempts; auto-expire (lockout) once the cap is hit. Returns the
    # updated pairing, or None if it no longer exists / is not pending.
    async def bump_channel_pairing_attempts(
        self, tenant_id: str, pairing_id: str, *, cap: int
    ) -> "ChannelPairing | None": ...
    async def add_memory_item(self, item: MemoryItem) -> None: ...
    async def query_memory(
        self, tenant_id: str, owner_scopes: list[str], kind: str | None = None, limit: int = 20
    ) -> list[MemoryItem]: ...

    # --- Round Five: structured memory governance (facts/ingestions/erasures) ---
    async def add_memory_fact(self, fact: MemoryFact) -> None: ...
    async def get_memory_fact(self, tenant_id: str, fact_id: str) -> MemoryFact | None: ...
    async def list_memory_facts(
        self, tenant_id: str, owner_scopes: list[str], kind: str | None = None, limit: int = 50
    ) -> list[MemoryFact]: ...
    async def delete_memory_fact(self, tenant_id: str, fact_id: str) -> None: ...
    async def add_memory_ingestion(self, ing: MemoryIngestion) -> None: ...
    async def update_memory_ingestion(self, ing: MemoryIngestion) -> None: ...
    async def list_memory_ingestions(self, tenant_id: str, limit: int = 50) -> list[MemoryIngestion]: ...
    async def add_memory_erasure(self, er: MemoryErasure) -> None: ...
    async def list_memory_erasures(self, tenant_id: str, limit: int = 50) -> list[MemoryErasure]: ...

    # --- Round Four: users + provisioning (USR), tokens (PAT), settings, sessions ---
    async def upsert_user(self, user: User) -> None: ...
    async def get_user(self, tenant_id: str, user_id: str) -> User | None: ...
    async def list_users(self, tenant_id: str) -> list[User]: ...
    async def add_pat(self, pat: PersonalAccessToken) -> None: ...
    async def get_pat(self, tenant_id: str, pat_id: str) -> PersonalAccessToken | None: ...
    async def get_pat_by_hash(self, token_hash: str) -> PersonalAccessToken | None: ...
    async def list_pats(self, tenant_id: str, user_id: str) -> list[PersonalAccessToken]: ...
    async def update_pat(self, pat: PersonalAccessToken) -> None: ...
    async def add_invitation(self, inv: UserInvitation) -> None: ...
    async def get_invitation(self, tenant_id: str, inv_id: str) -> UserInvitation | None: ...
    async def list_invitations(self, tenant_id: str) -> list[UserInvitation]: ...
    async def find_pending_invitation(
        self, tenant_id: str, email: str
    ) -> UserInvitation | None: ...
    async def update_invitation(self, inv: UserInvitation) -> None: ...
    async def upsert_user_setting(self, setting: UserSetting) -> None: ...
    async def list_user_settings(self, tenant_id: str, user_id: str) -> list[UserSetting]: ...
    async def add_session(self, session: UserSession) -> None: ...
    async def list_sessions(self, tenant_id: str, user_id: str) -> list[UserSession]: ...
    async def get_session(self, tenant_id: str, session_id: str) -> UserSession | None: ...
    async def update_session(self, session: UserSession) -> None: ...

    # --- conversations (Round Two, SEC-25 tenant + owner scoped) ---
    async def create_conversation(self, conv: Conversation) -> None: ...
    async def get_conversation(self, tenant_id: str, conv_id: str) -> Conversation | None: ...
    async def list_conversations(self, tenant_id: str, user_id: str) -> list[Conversation]: ...
    async def update_conversation(self, conv: Conversation) -> None: ...
    async def add_message(self, message: ConversationMessage) -> None: ...
    async def list_messages(
        self, tenant_id: str, conv_id: str
    ) -> list[ConversationMessage]: ...
    # Append-plus-supersede marker ([2026] VJS-COUNTY 4): set ONLY superseded_by on
    # the message, freezing everything else (content/events/run_id/created_at are
    # immutable). This is the marker-only write regenerate uses; add_message stays
    # insert-only, so there is no general-purpose message update. Tenant-scoped
    # (SEC-08).
    async def mark_message_superseded(
        self, tenant_id: str, message_id: str, superseded_by: str
    ) -> None: ...
    # Right-to-erasure (M11 / SEC-74): HARD-DELETE every CLOSED conversation whose
    # close/update timestamp is at or before ``older_than``, together with its
    # conversation_messages, and return how many conversations were purged. The
    # soft-close (DELETE /v1/me/conversations/{id}) only sets status=CLOSED; this
    # is the durable erasure the retention worker drives past the retention window
    # so a deleted thread's body does not persist indefinitely. Tenant-scoped
    # (SEC-08). The audit log is EXEMPT - erasing the tamper-evident hash chain
    # (SEC-16) would break verify() and the accountability record.
    async def purge_closed_conversations(
        self, tenant_id: str, older_than: datetime
    ) -> int: ...
