"""The Store protocol - the kernel's only persistence seam.

The kernel depends on this Protocol, never on a concrete DB. ``InMemoryStore``
satisfies it for dev/tests; a Postgres-backed store (schema in ``schema.sql``)
satisfies the same Protocol for production. Tenant isolation (SEC-08) is a
contract of every method: an id lookup is always scoped by ``tenant_id``.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from boltrig.models import (
    AdapterRecord,
    AgentCapability,
    AuditEvent,
    Budget,
    ConfigRevision,
    Conversation,
    ConversationMessage,
    EvalCase,
    EvalRun,
    HITLRequest,
    MemoryErasure,
    MemoryFact,
    MemoryIngestion,
    MemoryItem,
    NotificationPref,
    PersonalAccessToken,
    PersonalAgent,
    HITLResponse,
    ModelEndpoint,
    Noun,
    Skill,
    TenantPermissions,
    User,
    UserInvitation,
    UserSession,
    UserSetting,
    Verb,
    VerbBinding,
    WorkflowDefinition,
    WorkItem,
    WorkStatus,
)


@runtime_checkable
class Store(Protocol):
    # --- registry ---
    async def get_noun(self, tenant_id: str, noun_id: str) -> Noun | None: ...
    async def get_verb(self, tenant_id: str, verb_id: str) -> Verb | None: ...
    async def list_verbs(self, tenant_id: str, noun_id: str | None = None) -> list[Verb]: ...
    async def get_binding(self, tenant_id: str, verb_id: str) -> VerbBinding | None: ...
    async def upsert_noun(self, noun: Noun) -> None: ...
    async def upsert_verb(self, verb: Verb) -> None: ...
    async def upsert_binding(self, binding: VerbBinding) -> None: ...

    # --- permissions ---
    async def get_tenant_permissions(self, tenant_id: str) -> TenantPermissions: ...

    # --- libraries ---
    async def upsert_adapter(self, adapter: AdapterRecord) -> None: ...
    async def get_adapter(self, tenant_id: str, adapter_id: str) -> AdapterRecord | None: ...
    async def list_adapters(self, tenant_id: str) -> list[AdapterRecord]: ...
    async def upsert_skill(self, skill: Skill) -> None: ...
    async def get_skill(self, tenant_id: str, skill_id: str) -> Skill | None: ...
    async def list_skills(self, tenant_id: str) -> list[Skill]: ...
    async def upsert_capability(self, cap: AgentCapability) -> None: ...
    async def list_capabilities(self, tenant_id: str) -> list[AgentCapability]: ...
    async def upsert_workflow(self, wf: WorkflowDefinition) -> None: ...
    async def list_workflows(self, tenant_id: str) -> list[WorkflowDefinition]: ...
    async def upsert_model_endpoint(self, ep: ModelEndpoint) -> None: ...
    async def get_model_endpoint(self, tenant_id: str, ep_id: str) -> ModelEndpoint | None: ...

    # --- work items ---
    async def create_work_item(self, item: WorkItem) -> None: ...
    async def get_work_item(self, tenant_id: str, item_id: str) -> WorkItem | None: ...
    async def update_work_item(self, item: WorkItem) -> None: ...
    async def list_work_items(
        self,
        tenant_id: str,
        status: WorkStatus | None = None,
        parent_id: str | None = None,
        departments: list[str] | None = None,
    ) -> list[WorkItem]: ...

    # --- hitl ---
    async def create_hitl_request(self, req: HITLRequest) -> None: ...
    async def get_hitl_request(self, tenant_id: str, req_id: str) -> HITLRequest | None: ...
    async def list_pending_hitl(self, tenant_id: str) -> list[HITLRequest]: ...
    async def answer_hitl(self, resp: HITLResponse) -> HITLRequest | None: ...
    async def get_hitl_response(
        self, tenant_id: str, request_id: str
    ) -> HITLResponse | None: ...

    # --- audit (hash chain head + append + query) ---
    async def audit_head(self, tenant_id: str) -> tuple[int, str | None]: ...
    async def audit_append(self, event: AuditEvent) -> None: ...
    async def audit_query(
        self, tenant_id: str, run_id: str | None = None, limit: int = 200
    ) -> list[AuditEvent]: ...

    # --- budgets ---
    async def get_budget(self, tenant_id: str, scope_id: str) -> Budget | None: ...
    async def list_budgets(self, tenant_id: str) -> list[Budget]: ...
    async def consume_budget(
        self, tenant_id: str, scope_id: str, tokens: int, micros: int
    ) -> bool: ...

    # --- idempotency (NFR-REL-02) ---
    async def idempotency_get(self, tenant_id: str, key: str) -> dict | None: ...
    async def idempotency_put(self, tenant_id: str, key: str, result: dict) -> None: ...

    # --- credential references (refs only; never plaintext, SEC-04) ---
    async def get_credential_ref(self, tenant_id: str, cred_id: str) -> dict | None: ...

    # --- Round Three: versioned config, eval, customisation, memory ---
    async def add_config_revision(self, rev: ConfigRevision) -> ConfigRevision: ...
    async def list_config_revisions(
        self, tenant_id: str, kind: str, ref: str
    ) -> list[ConfigRevision]: ...
    async def get_config_revision(self, tenant_id: str, rev_id: int) -> ConfigRevision | None: ...
    async def upsert_eval_case(self, case: EvalCase) -> None: ...
    async def get_eval_case(self, tenant_id: str, case_id: str) -> EvalCase | None: ...
    async def list_eval_cases(self, tenant_id: str) -> list[EvalCase]: ...
    async def add_eval_run(self, run: EvalRun) -> None: ...
    async def list_eval_runs(
        self, tenant_id: str, case_id: str | None = None
    ) -> list[EvalRun]: ...
    async def upsert_notification_pref(self, pref: NotificationPref) -> None: ...
    async def list_notification_prefs(self, tenant_id: str) -> list[NotificationPref]: ...
    async def upsert_personal_agent(self, agent: PersonalAgent) -> None: ...
    async def get_personal_agent(self, tenant_id: str, user_id: str) -> PersonalAgent | None: ...
    async def add_memory_item(self, item: MemoryItem) -> None: ...
    async def query_memory(
        self, tenant_id: str, owner_scopes: list[str], kind: str | None = None, limit: int = 20
    ) -> list[MemoryItem]: ...

    # --- Round Five: structured memory governance (facts/ingestions/erasures) ---
    async def add_memory_fact(self, fact: MemoryFact) -> None: ...
    async def get_memory_fact(self, tenant_id: str, fact_id: str) -> MemoryFact | None: ...
    async def list_memory_facts(
        self, tenant_id: str, owner_scopes: list[str], kind: str | None = None, limit: int = 50
    ) -> list[MemoryFact]: ...
    async def delete_memory_fact(self, tenant_id: str, fact_id: str) -> None: ...
    async def add_memory_ingestion(self, ing: MemoryIngestion) -> None: ...
    async def update_memory_ingestion(self, ing: MemoryIngestion) -> None: ...
    async def list_memory_ingestions(self, tenant_id: str, limit: int = 50) -> list[MemoryIngestion]: ...
    async def add_memory_erasure(self, er: MemoryErasure) -> None: ...
    async def list_memory_erasures(self, tenant_id: str, limit: int = 50) -> list[MemoryErasure]: ...

    # --- Round Four: users + provisioning (USR), tokens (PAT), settings, sessions ---
    async def upsert_user(self, user: User) -> None: ...
    async def get_user(self, tenant_id: str, user_id: str) -> User | None: ...
    async def list_users(self, tenant_id: str) -> list[User]: ...
    async def add_pat(self, pat: PersonalAccessToken) -> None: ...
    async def get_pat(self, tenant_id: str, pat_id: str) -> PersonalAccessToken | None: ...
    async def get_pat_by_hash(self, token_hash: str) -> PersonalAccessToken | None: ...
    async def list_pats(self, tenant_id: str, user_id: str) -> list[PersonalAccessToken]: ...
    async def update_pat(self, pat: PersonalAccessToken) -> None: ...
    async def add_invitation(self, inv: UserInvitation) -> None: ...
    async def get_invitation(self, tenant_id: str, inv_id: str) -> UserInvitation | None: ...
    async def list_invitations(self, tenant_id: str) -> list[UserInvitation]: ...
    async def find_pending_invitation(
        self, tenant_id: str, email: str
    ) -> UserInvitation | None: ...
    async def update_invitation(self, inv: UserInvitation) -> None: ...
    async def upsert_user_setting(self, setting: UserSetting) -> None: ...
    async def list_user_settings(self, tenant_id: str, user_id: str) -> list[UserSetting]: ...
    async def add_session(self, session: UserSession) -> None: ...
    async def list_sessions(self, tenant_id: str, user_id: str) -> list[UserSession]: ...
    async def get_session(self, tenant_id: str, session_id: str) -> UserSession | None: ...
    async def update_session(self, session: UserSession) -> None: ...

    # --- conversations (Round Two, SEC-25 tenant + owner scoped) ---
    async def create_conversation(self, conv: Conversation) -> None: ...
    async def get_conversation(self, tenant_id: str, conv_id: str) -> Conversation | None: ...
    async def list_conversations(self, tenant_id: str, user_id: str) -> list[Conversation]: ...
    async def update_conversation(self, conv: Conversation) -> None: ...
    async def add_message(self, message: ConversationMessage) -> None: ...
    async def list_messages(
        self, tenant_id: str, conv_id: str
    ) -> list[ConversationMessage]: ...
