"""Boltrig domain models.

Domain state is frozen dataclasses (immutable, hashable); API request/response
bodies are Pydantic and live with the FastAPI app.
"""

from __future__ import annotations

from .audit import ActionType, AuditEvent
from .base import (
    AdapterId,
    CapabilityName,
    HITLId,
    NounId,
    OrgId,
    RunId,
    SkillId,
    TenantId,
    UserId,
    VerbId,
    WorkflowId,
    WorkItemId,
    WorkspaceId,
    utcnow,
)
from .channels import (
    CHANNEL_PLATFORMS,
    SOCKET_PLATFORMS,
    UNPAIRED_BEHAVIORS,
    WEBHOOK_PLATFORMS,
    Channel,
    ChannelBinding,
    ChannelPairing,
    transport_for,
)
from .context import InvocationContext
from .conversation import (
    Conversation,
    ConversationMessage,
    ConversationStatus,
    ConversationSummary,
    MessageRole,
)
from .platform import (
    ConfigRevision,
    EvalCase,
    EvalRun,
    MemoryItem,
    NotificationPref,
    PersonalAgent,
)
from .errors import (
    BindingNotFound,
    BudgetExceeded,
    ContextRequirementsUnmet,
    CredentialResolution,
    DegradedMode,
    DepthExceeded,
    GrantMissing,
    BoltrigError,
    NetworkPolicyViolation,
    PendingHuman,
    RateLimited,
    SchemaValidationError,
    SensitiveDataMisrouted,
    TenantIsolation,
)
from .access import (
    PersonalAccessToken,
    UserInvitation,
    UserSession,
    UserSetting,
)
from .grants import EMPTY_GRANTS, GrantSet, TenantPermissions
from .hitl import HITLRequest, HITLResponse, HITLStatus, HITLType, Urgency
from .identity import RoleMapping, User
from .memory import MemoryErasure, MemoryFact, MemoryIngestion
from .libraries import (
    AdapterHealth,
    AdapterRecord,
    AgentCapability,
    Budget,
    ModelEndpoint,
    PromotionState,
    Skill,
    WorkflowDefinition,
    WorkflowPromotion,
    WorkflowSource,
)
from .registry import Consequence, Noun, RateLimit, TargetType, Verb, VerbBinding
from .tenancy import (
    AI_CONFIG_LEVELS,
    WORKSPACE_ROLES,
    AiConfig,
    OrgMember,
    Organisation,
    Workspace,
    WorkspaceMember,
)
from .work import RunCheckpoint, WorkItem, WorkStatus

__all__ = [
    "ActionType",
    "AuditEvent",
    "AdapterId",
    "CapabilityName",
    "HITLId",
    "NounId",
    "OrgId",
    "RunId",
    "SkillId",
    "TenantId",
    "UserId",
    "VerbId",
    "WorkflowId",
    "WorkItemId",
    "WorkspaceId",
    "utcnow",
    "InvocationContext",
    "Channel",
    "ChannelBinding",
    "ChannelPairing",
    "CHANNEL_PLATFORMS",
    "SOCKET_PLATFORMS",
    "WEBHOOK_PLATFORMS",
    "UNPAIRED_BEHAVIORS",
    "transport_for",
    "Conversation",
    "ConversationMessage",
    "ConversationStatus",
    "ConversationSummary",
    "MessageRole",
    "ConfigRevision",
    "EvalCase",
    "EvalRun",
    "MemoryItem",
    "MemoryFact",
    "MemoryIngestion",
    "MemoryErasure",
    "NotificationPref",
    "PersonalAgent",
    "BoltrigError",
    "SchemaValidationError",
    "BindingNotFound",
    "GrantMissing",
    "TenantIsolation",
    "RateLimited",
    "BudgetExceeded",
    "DepthExceeded",
    "ContextRequirementsUnmet",
    "CredentialResolution",
    "NetworkPolicyViolation",
    "SensitiveDataMisrouted",
    "PendingHuman",
    "DegradedMode",
    "EMPTY_GRANTS",
    "GrantSet",
    "TenantPermissions",
    "HITLRequest",
    "HITLResponse",
    "HITLStatus",
    "HITLType",
    "Urgency",
    "RoleMapping",
    "User",
    "PersonalAccessToken",
    "UserInvitation",
    "UserSession",
    "UserSetting",
    "AdapterHealth",
    "AdapterRecord",
    "AgentCapability",
    "Budget",
    "ModelEndpoint",
    "PromotionState",
    "Skill",
    "WorkflowDefinition",
    "WorkflowPromotion",
    "WorkflowSource",
    "Consequence",
    "Noun",
    "RateLimit",
    "TargetType",
    "Verb",
    "VerbBinding",
    "WORKSPACE_ROLES",
    "AI_CONFIG_LEVELS",
    "AiConfig",
    "Organisation",
    "Workspace",
    "OrgMember",
    "WorkspaceMember",
    "RunCheckpoint",
    "WorkItem",
    "WorkStatus",
]
