import SwiftUI

/// The last step: setup is saved, Familiar is here, and the one line that says where
/// replies come from. The frame's button reads "Start".
struct ReadyStepView: View {
    let name: String

    var body: some View {
        OnboardingCard(kicker: "Setup complete", title: "You're ready, \(name). Meet Familiar.") {
            HStack {
                Spacer()
                FamiliarPresenceView(surface: "onboarding", presentation: .hero, mode: .standby, size: 160)
                Spacer()
            }
            .padding(.vertical, 8)
            Text("Replies are generated by the AI you connected.")
                .font(.footnote)
                .foregroundStyle(.secondary)
                .frame(maxWidth: .infinity, alignment: .center)
                .multilineTextAlignment(.center)
        }
    }
}
