"""Deterministic TOML rendering for the pinned secretless Codex cell config."""

from __future__ import annotations

import hashlib
import json
import tomllib
from collections.abc import Mapping
from types import MappingProxyType

CODEX_MODEL_PROVIDER_ID = "boltrig_model_proxy"
# Shared with codex_runtime_config_argv: the same provider identity is pinned on
# argv and rendered into the TOML, so it lives in ONE place rather than being
# written out twice and hoped to match ([2026] VJS-CC-VJS 6 H5).
CODEX_RUNTIME_PROVIDER_NAME = "Boltrig per-cell model proxy"
CODEX_RUNTIME_WIRE_API = "responses"
# The ONE MCP server a kernel-tools cell may carry: the kernel's own MCP face.
# The server name is part of the model-facing tool names (``mcp__boltrig__*``),
# so it is a fixed constant, never a per-run value. The bearer travels ONLY in
# the named environment variable at spawn time - never in this file, never on
# argv (see codex_kernel_tool_scope).
CODEX_MCP_SERVER_NAME = "boltrig"
CODEX_MCP_BEARER_ENV_VAR = "BOLTRIG_CODEX_MCP_RUN_TOKEN"
_PROVIDER_FIELDS = (
    "name",
    "base_url",
    "wire_api",
    "request_max_retries",
    "stream_max_retries",
    "stream_idle_timeout_ms",
    "supports_websockets",
    "auth.command",
    "auth.args",
    "auth.timeout_ms",
    "auth.refresh_interval_ms",
)
CODEX_RUNTIME_PROVIDER_CONTRACT_DIGEST = "sha256:" + hashlib.sha256(
    json.dumps(_PROVIDER_FIELDS, ensure_ascii=True, separators=(",", ":")).encode("ascii")
).hexdigest()
CODEX_RUNTIME_DISABLED_FEATURES: Mapping[str, bool] = MappingProxyType(
    {
        "apps": False,
        "auth_elicitation": False,
        "browser_use": False,
        "browser_use_external": False,
        "browser_use_full_cdp_access": False,
        "code_mode_host": False,
        "computer_use": False,
        "hooks": False,
        "image_generation": False,
        "in_app_browser": False,
        "memories": False,
        "multi_agent": False,
        "plugins": False,
        "plugin_sharing": False,
        "remote_plugin": False,
        "request_permissions_tool": False,
        "skill_mcp_dependency_install": False,
        "tool_call_mcp_elicitation": False,
        "workspace_dependencies": False,
    }
)
_ROOT_KEYS = frozenset(
    {
        "agents",
        "analytics",
        "apps",
        "approval_policy",
        "check_for_update_on_startup",
        "features",
        "feedback",
        "history",
        "mcp_servers",
        "model",
        "model_provider",
        "model_providers",
        "model_reasoning_effort",
        "personality",
        "project_doc_fallback_filenames",
        "project_doc_max_bytes",
        "project_root_markers",
        "sandbox_mode",
        "shell_environment_policy",
        "skills",
        "web_search",
    }
)


def _string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def _boolean(value: bool) -> str:
    return "true" if value else "false"


def _root_lines(*, model_id: str, reasoning_effort: str) -> list[str]:
    return [
        "# Generated by Boltrig for the reviewed Codex 0.144.3 contract.",
        "# Do not merge user, project, environment, or CLI override fields.",
        f"model = {_string(model_id)}",
        f"model_provider = {_string(CODEX_MODEL_PROVIDER_ID)}",
        f"model_reasoning_effort = {_string(reasoning_effort)}",
        'personality = "none"',
        'approval_policy = "never"',
        'sandbox_mode = "read-only"',
        'web_search = "disabled"',
        "check_for_update_on_startup = false",
        "project_doc_max_bytes = 0",
        "project_doc_fallback_filenames = []",
        "project_root_markers = []",
    ]


def _policy_lines(*, agents_enabled: bool) -> list[str]:
    return [
        "",
        "[agents]",
        f"max_threads = {4 if agents_enabled else 1}",
        "max_depth = 1",
        "",
        "[analytics]",
        "enabled = false",
        "",
        "[feedback]",
        "enabled = false",
        "",
        "[history]",
        'persistence = "none"',
        "",
        "[shell_environment_policy]",
        'inherit = "none"',
        "ignore_default_excludes = false",
        "exclude = []",
        "set = {}",
        "include_only = []",
        "experimental_use_profile = false",
    ]


def _feature_lines(features: Mapping[str, bool], *, apps_enabled: bool) -> list[str]:
    lines = ["", "[features]"]
    lines.extend(f"{name} = {_boolean(features[name])}" for name in sorted(features))
    lines.extend(
        (
            "",
            "[apps._default]",
            f"enabled = {_boolean(apps_enabled)}",
        )
    )
    return lines


def _mcp_lines(mcp_server_url: str | None, mcp_bearer_env_var: str | None) -> list[str]:
    """The ``[mcp_servers]`` section: empty, or exactly the kernel's own face.

    The read-only lane renders the bare empty table (byte-identical to before).
    The kernel-tools lane renders ONE server entry pointing at the kernel's
    ``POST /v1/mcp``; the bearer is named by ENV VAR only, so the run-scoped
    token never lands in this file.
    """

    if mcp_server_url is None and mcp_bearer_env_var is None:
        return ["", "[mcp_servers]"]
    if type(mcp_server_url) is not str or type(mcp_bearer_env_var) is not str:
        raise ValueError("MCP server url and bearer env var must be paired strings")
    return [
        "",
        f"[mcp_servers.{CODEX_MCP_SERVER_NAME}]",
        f"url = {_string(mcp_server_url)}",
        f"bearer_token_env_var = {_string(mcp_bearer_env_var)}",
    ]


def _skill_lines(entries: tuple[tuple[str, bool], ...]) -> list[str]:
    lines: list[str] = []
    for path, enabled in entries:
        lines.extend(
            (
                "",
                "[[skills.config]]",
                f"path = {_string(path)}",
                f"enabled = {_boolean(enabled)}",
            )
        )
    return lines


def _provider_lines(
    *, cell_id: str, helper_path: str, socket_name: str, proxy_port: int
) -> list[str]:
    provider = f"model_providers.{CODEX_MODEL_PROVIDER_ID}"
    return [
        "",
        f"[{provider}]",
        f"name = {_string(CODEX_RUNTIME_PROVIDER_NAME)}",
        f'base_url = "http://127.0.0.1:{proxy_port}/v1"',
        f"wire_api = {_string(CODEX_RUNTIME_WIRE_API)}",
        "request_max_retries = 0",
        "stream_max_retries = 0",
        "stream_idle_timeout_ms = 300000",
        "supports_websockets = false",
        "",
        f"[{provider}.auth]",
        # G2: one shared, root-owned, non-writable helper for every cell. Every
        # per-cell value travels on argv, because the program itself must be
        # identical for all cells or it is writable by one of them.
        f"command = {_string(helper_path)}",
        f"args = [{_string('--cell-id')}, {_string(cell_id)}, "
        f"{_string('--socket')}, {_string(socket_name)}]",
        "timeout_ms = 1000",
        "refresh_interval_ms = 30000",
    ]


def _render_codex_runtime_config(
    *,
    model_id: str,
    reasoning_effort: str,
    cell_id: str,
    helper_path: str,
    socket_name: str,
    proxy_port: int,
    features: Mapping[str, bool],
    skill_entries: tuple[tuple[str, bool], ...],
    mcp_server_url: str | None = None,
    mcp_bearer_env_var: str | None = None,
) -> str:
    """Render one complete ASCII TOML document from validated values."""

    agents_enabled = features["multi_agent"]
    apps_enabled = features["apps"]
    lines = _root_lines(model_id=model_id, reasoning_effort=reasoning_effort)
    lines.extend(_policy_lines(agents_enabled=agents_enabled))
    lines.extend(_feature_lines(features, apps_enabled=apps_enabled))
    lines.extend(_mcp_lines(mcp_server_url, mcp_bearer_env_var))
    lines.extend(_skill_lines(skill_entries))
    lines.extend(
        _provider_lines(
            cell_id=cell_id,
            helper_path=helper_path,
            socket_name=socket_name,
            proxy_port=proxy_port,
        )
    )
    return "\n".join(lines) + "\n"


def canonical_skill_entries_digest(entries: tuple[tuple[str, bool], ...]) -> str:
    encoded = json.dumps(entries, ensure_ascii=True, separators=(",", ":")).encode("ascii")
    return "sha256:" + hashlib.sha256(encoded).hexdigest()


def _runtime_config_skill_entries(
    config_toml: str,
) -> tuple[tuple[str, bool], ...] | None:
    try:
        document = tomllib.loads(config_toml)
    except (UnicodeError, tomllib.TOMLDecodeError):
        return None
    if type(document) is not dict or set(document) != _ROOT_KEYS:
        return None
    skills = document.get("skills")
    if type(skills) is not dict or set(skills) != {"config"}:
        return None
    raw_entries = skills.get("config")
    if type(raw_entries) is not list:
        return None
    entries: list[tuple[str, bool]] = []
    for raw in raw_entries:
        if type(raw) is not dict or set(raw) != {"path", "enabled"}:
            return None
        path, enabled = raw.get("path"), raw.get("enabled")
        if type(path) is not str or type(enabled) is not bool:
            return None
        entries.append((path, enabled))
    return tuple(entries)


def runtime_config_matches_receipt(
    config_toml: str,
    *,
    model_id: str,
    reasoning_effort: str,
    cell_id: str,
    helper_path: str,
    socket_name: str,
    proxy_port: int,
    provider_id: str,
    skill_entries: tuple[tuple[str, bool], ...],
    skill_entries_digest: str,
    mcp_server_url: str | None = None,
    mcp_bearer_env_var: str | None = None,
) -> bool:
    """Check every receipt claim represented by the rendered TOML contract."""

    parsed_entries = _runtime_config_skill_entries(config_toml)
    if parsed_entries is None or parsed_entries != skill_entries:
        return False
    if canonical_skill_entries_digest(parsed_entries) != skill_entries_digest:
        return False
    if provider_id != CODEX_MODEL_PROVIDER_ID:
        return False
    expected = _render_codex_runtime_config(
        model_id=model_id,
        reasoning_effort=reasoning_effort,
        cell_id=cell_id,
        helper_path=helper_path,
        socket_name=socket_name,
        proxy_port=proxy_port,
        features=CODEX_RUNTIME_DISABLED_FEATURES,
        skill_entries=parsed_entries,
        mcp_server_url=mcp_server_url,
        mcp_bearer_env_var=mcp_bearer_env_var,
    )
    return config_toml == expected


__all__ = [
    "CODEX_MCP_BEARER_ENV_VAR",
    "CODEX_MCP_SERVER_NAME",
    "CODEX_MODEL_PROVIDER_ID",
    "CODEX_RUNTIME_DISABLED_FEATURES",
    "CODEX_RUNTIME_PROVIDER_CONTRACT_DIGEST",
    "canonical_skill_entries_digest",
    "runtime_config_matches_receipt",
]
