"""The Store protocol - the kernel's only persistence seam.

The kernel depends on this Protocol, never on a concrete DB. ``InMemoryStore``
satisfies it for dev/tests; a Postgres-backed store (schema in ``schema.sql``)
satisfies the same Protocol for production. Tenant isolation (SEC-08) is a
contract of every method: an id lookup is always scoped by ``tenant_id``.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from nankle.models import (
    AdapterRecord,
    AgentCapability,
    AuditEvent,
    Budget,
    HITLRequest,
    HITLResponse,
    ModelEndpoint,
    Noun,
    Skill,
    TenantPermissions,
    Verb,
    VerbBinding,
    WorkflowDefinition,
    WorkItem,
    WorkStatus,
)


@runtime_checkable
class Store(Protocol):
    # --- registry ---
    async def get_noun(self, tenant_id: str, noun_id: str) -> Noun | None: ...
    async def get_verb(self, tenant_id: str, verb_id: str) -> Verb | None: ...
    async def list_verbs(self, tenant_id: str, noun_id: str | None = None) -> list[Verb]: ...
    async def get_binding(self, tenant_id: str, verb_id: str) -> VerbBinding | None: ...
    async def upsert_noun(self, noun: Noun) -> None: ...
    async def upsert_verb(self, verb: Verb) -> None: ...
    async def upsert_binding(self, binding: VerbBinding) -> None: ...

    # --- permissions ---
    async def get_tenant_permissions(self, tenant_id: str) -> TenantPermissions: ...

    # --- libraries ---
    async def upsert_adapter(self, adapter: AdapterRecord) -> None: ...
    async def get_adapter(self, tenant_id: str, adapter_id: str) -> AdapterRecord | None: ...
    async def list_adapters(self, tenant_id: str) -> list[AdapterRecord]: ...
    async def upsert_skill(self, skill: Skill) -> None: ...
    async def get_skill(self, tenant_id: str, skill_id: str) -> Skill | None: ...
    async def upsert_capability(self, cap: AgentCapability) -> None: ...
    async def list_capabilities(self, tenant_id: str) -> list[AgentCapability]: ...
    async def upsert_workflow(self, wf: WorkflowDefinition) -> None: ...
    async def list_workflows(self, tenant_id: str) -> list[WorkflowDefinition]: ...
    async def upsert_model_endpoint(self, ep: ModelEndpoint) -> None: ...
    async def get_model_endpoint(self, tenant_id: str, ep_id: str) -> ModelEndpoint | None: ...

    # --- work items ---
    async def create_work_item(self, item: WorkItem) -> None: ...
    async def get_work_item(self, tenant_id: str, item_id: str) -> WorkItem | None: ...
    async def update_work_item(self, item: WorkItem) -> None: ...
    async def list_work_items(
        self,
        tenant_id: str,
        status: WorkStatus | None = None,
        parent_id: str | None = None,
        departments: list[str] | None = None,
    ) -> list[WorkItem]: ...

    # --- hitl ---
    async def create_hitl_request(self, req: HITLRequest) -> None: ...
    async def get_hitl_request(self, tenant_id: str, req_id: str) -> HITLRequest | None: ...
    async def list_pending_hitl(self, tenant_id: str) -> list[HITLRequest]: ...
    async def answer_hitl(self, resp: HITLResponse) -> HITLRequest | None: ...
    async def get_hitl_response(
        self, tenant_id: str, request_id: str
    ) -> HITLResponse | None: ...

    # --- audit (hash chain head + append + query) ---
    async def audit_head(self, tenant_id: str) -> tuple[int, str | None]: ...
    async def audit_append(self, event: AuditEvent) -> None: ...
    async def audit_query(
        self, tenant_id: str, run_id: str | None = None, limit: int = 200
    ) -> list[AuditEvent]: ...

    # --- budgets ---
    async def get_budget(self, tenant_id: str, scope_id: str) -> Budget | None: ...
    async def consume_budget(
        self, tenant_id: str, scope_id: str, tokens: int, micros: int
    ) -> bool: ...

    # --- idempotency (NFR-REL-02) ---
    async def idempotency_get(self, tenant_id: str, key: str) -> dict | None: ...
    async def idempotency_put(self, tenant_id: str, key: str, result: dict) -> None: ...

    # --- credential references (refs only; never plaintext, SEC-04) ---
    async def get_credential_ref(self, tenant_id: str, cred_id: str) -> dict | None: ...
