"""Supply-chain contract for the standalone Pi sidecar dependency graph."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml


_REPO = Path(__file__).resolve().parents[2]


def _text(path: str) -> str:
    return (_REPO / path).read_text()


@pytest.mark.security
@pytest.mark.invariant("IAC-002")
def test_pi_sidecar_uses_python312_generated_full_hash_lock() -> None:
    source = _text("services/pi_sidecar/requirements.in")
    lock = _text("services/pi_sidecar/requirements.txt")
    dockerfile = _text("services/pi_sidecar/Dockerfile")

    direct = {
        line.strip()
        for line in source.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }
    assert direct == {"fastapi==0.139.0", "httpx==0.28.1", "uvicorn[standard]==0.49.0"}
    assert "autogenerated by pip-compile with Python 3.12" in lock
    assert "--hash=sha256:" in lock
    assert "annotated-types==" in lock
    assert "pydantic-core==" in lock
    assert "pip install --require-hashes -r /app/requirements.txt" in dockerfile


@pytest.mark.security
@pytest.mark.invariant("IAC-002")
def test_pi_sidecar_lock_is_audited_and_dependabot_managed() -> None:
    makefile = _text("Makefile")
    dependabot = yaml.safe_load(_text(".github/dependabot.yml"))

    assert (
        "--require-hashes -r services/pi_sidecar/requirements.txt" in makefile
    )
    updates = dependabot["updates"]
    assert any(
        update["package-ecosystem"] == "pip"
        and update["directory"] == "/services/pi_sidecar"
        for update in updates
    )


@pytest.mark.security
@pytest.mark.invariant("IAC-003")
def test_iac_scan_is_pinned_offline_blocking_and_ci_enforced() -> None:
    makefile = _text("Makefile")
    workflow = _text(".github/workflows/security.yml")
    ignore = yaml.safe_load(_text(".trivyignore.yaml"))

    assert "aquasec/trivy:0.72.0@sha256:" in makefile
    assert "--skip-check-update --skip-version-check" in makefile
    assert "--severity HIGH,CRITICAL --exit-code 1" in makefile
    assert "make python-audit sast iac-scan PY=python" in workflow
    exceptions = ignore["misconfigurations"]
    assert exceptions
    assert all(item.get("paths") and item.get("expired_at") and item.get("statement") for item in exceptions)
