"""Supply-chain contract for the standalone Pi sidecar dependency graph."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml


_REPO = Path(__file__).resolve().parents[2]


def _text(path: str) -> str:
    return (_REPO / path).read_text()


@pytest.mark.security
@pytest.mark.invariant("IAC-002")
def test_pi_sidecar_uses_python312_generated_full_hash_lock() -> None:
    source = _text("services/pi_sidecar/requirements.in")
    lock = _text("services/pi_sidecar/requirements.txt")
    dockerfile = _text("services/pi_sidecar/Dockerfile")

    direct = {
        line.strip()
        for line in source.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }
    # DERIVED, not restated. This asserted the three exact version strings until
    # 2026-07-27, when a routine fastapi/uvicorn bump (#60) could not be merged by anyone
    # or anything: dependabot rewrote requirements.in, this line still named the old
    # versions, and no rebase could ever clear it. The property that matters is not WHICH
    # versions, it is that every direct requirement is exactly pinned and that the lock
    # actually contains it - which is what makes `--require-hashes` meaningful. Restating
    # the versions here made the test a second place to maintain them, and the second place
    # is always the one that goes stale.
    assert direct, "requirements.in declares no direct requirements"
    for req in sorted(direct):
        assert "==" in req, f"{req} is not exactly pinned, so the lock is not reproducible"
        name, _, version = req.partition("==")
        name = name.split("[")[0]
        # The VERSION, not merely the name. A first cut of this checked only that the name
        # appeared in the lock, and it passed on the exact drift it was written to catch:
        # bumping requirements.in without recompiling leaves the lock installing the old
        # release, and `--require-hashes` then reproduces the WRONG thing faithfully. Same
        # defect as the browser-cli override that shipped inert on the same day.
        assert f"\n{name}=={version}" in f"\n{lock}", (
            f"{name} is pinned to {version} in requirements.in and the lock does not install "
            f"that version. The lock was not recompiled, so the image ships the old release."
        )
    assert "autogenerated by pip-compile with Python 3.12" in lock
    assert "--hash=sha256:" in lock
    assert "annotated-types==" in lock
    assert "pydantic-core==" in lock
    assert "pip install --require-hashes -r /app/requirements.txt" in dockerfile


@pytest.mark.security
@pytest.mark.invariant("IAC-002")
def test_pi_sidecar_lock_is_audited_and_dependabot_managed() -> None:
    makefile = _text("Makefile")
    dependabot = yaml.safe_load(_text(".github/dependabot.yml"))

    assert (
        "--require-hashes -r services/pi_sidecar/requirements.txt" in makefile
    )
    updates = dependabot["updates"]
    assert any(
        update["package-ecosystem"] == "pip"
        and update["directory"] == "/services/pi_sidecar"
        for update in updates
    )


@pytest.mark.security
@pytest.mark.invariant("IAC-003")
def test_iac_scan_is_pinned_offline_blocking_and_ci_enforced() -> None:
    makefile = _text("Makefile")
    workflow = _text(".github/workflows/security.yml")
    ignore = yaml.safe_load(_text(".trivyignore.yaml"))

    assert "aquasec/trivy:0.72.0@sha256:" in makefile
    assert "--skip-check-update --skip-version-check" in makefile
    assert "--severity HIGH,CRITICAL --exit-code 1" in makefile
    assert "make python-audit sast iac-scan PY=python" in workflow
    exceptions = ignore["misconfigurations"]
    assert exceptions
    assert all(item.get("paths") and item.get("expired_at") and item.get("statement") for item in exceptions)
