// Colossus's ticker glyph atlas.
//
// GENERATED by components/colossus/scripts/gen_ticker_font.py -- do not
// hand-edit. Both halves come out of one table on purpose: the CPU compiles a
// ticker string to glyph ids and the GPU draws the bitmaps for those ids, so a
// map and an atlas that disagree is a panel confidently spelling something
// else. Regenerate rather than patching one side.
//
// 45 glyphs: 0..25 A-Z, 26..35 0-9, 36 space, then punctuation.

/** Char -> glyph id. Anything absent becomes a space, never an exception:
 *  a ticker is decoration on a running system and must not throw over a
 *  character somebody typed. */
const INDEX: Readonly<Record<string, number>> = {
  "A": 0,
  "B": 1,
  "C": 2,
  "D": 3,
  "E": 4,
  "F": 5,
  "G": 6,
  "H": 7,
  "I": 8,
  "J": 9,
  "K": 10,
  "L": 11,
  "M": 12,
  "N": 13,
  "O": 14,
  "P": 15,
  "Q": 16,
  "R": 17,
  "S": 18,
  "T": 19,
  "U": 20,
  "V": 21,
  "W": 22,
  "X": 23,
  "Y": 24,
  "Z": 25,
  "0": 26,
  "1": 27,
  "2": 28,
  "3": 29,
  "4": 30,
  "5": 31,
  "6": 32,
  "7": 33,
  "8": 34,
  "9": 35,
  " ": 36,
  ".": 37,
  "-": 38,
  ",": 39,
  ":": 40,
  "/": 41,
  "+": 42,
  "%": 43,
  "*": 44,
};

export const TICKER_GLYPH_COUNT = 45;

/** Compile text to glyph ids. Case-folded up, unknowns to space. */
export function glyphIds(text: string): number[] {
  const upper = text.toUpperCase();
  const ids: number[] = [];
  for (const ch of upper) ids.push(INDEX[ch] ?? INDEX[" "]);
  return ids;
}

/** The atlas and its sampler, spliced into the panel fragment shader. */
export const GLYPH_GLSL = `
const int GLYPH_COUNT = 45;
const uvec2 FONT[45] = uvec2[45](
    uvec2(0xFC62Eu, 0x4631u),  //  0  A
    uvec2(0xF463Eu, 0x7A31u),  //  1  B
    uvec2(0x8422Eu, 0x3A30u),  //  2  C
    uvec2(0x8C63Eu, 0x7A31u),  //  3  D
    uvec2(0xF421Fu, 0x7E10u),  //  4  E
    uvec2(0xF421Fu, 0x4210u),  //  5  F
    uvec2(0xBC22Eu, 0x3E31u),  //  6  G
    uvec2(0xFC631u, 0x4631u),  //  7  H
    uvec2(0x2108Eu, 0x3884u),  //  8  I
    uvec2(0x10847u, 0x3242u),  //  9  J
    uvec2(0xC5251u, 0x4654u),  // 10  K
    uvec2(0x84210u, 0x7E10u),  // 11  L
    uvec2(0xAD771u, 0x4631u),  // 12  M
    uvec2(0x9D731u, 0x4631u),  // 13  N
    uvec2(0x8C62Eu, 0x3A31u),  // 14  O
    uvec2(0xF463Eu, 0x4210u),  // 15  P
    uvec2(0x8C62Eu, 0x3655u),  // 16  Q
    uvec2(0xF463Eu, 0x4654u),  // 17  R
    uvec2(0x7420Fu, 0x7821u),  // 18  S
    uvec2(0x2109Fu, 0x1084u),  // 19  T
    uvec2(0x8C631u, 0x3A31u),  // 20  U
    uvec2(0x8C631u, 0x1151u),  // 21  V
    uvec2(0xAC631u, 0x2AB5u),  // 22  W
    uvec2(0x22A31u, 0x462Au),  // 23  X
    uvec2(0x22A31u, 0x1084u),  // 24  Y
    uvec2(0x2083Fu, 0x7E08u),  // 25  Z
    uvec2(0xACE2Eu, 0x3A39u),  // 26  0
    uvec2(0x21184u, 0x3884u),  // 27  1
    uvec2(0x1062Eu, 0x7D04u),  // 28  2
    uvec2(0x1105Fu, 0x3A21u),  // 29  3
    uvec2(0x928C2u, 0x085Fu),  // 30  4
    uvec2(0x0FA1Fu, 0x3A21u),  // 31  5
    uvec2(0xF4106u, 0x3A31u),  // 32  6
    uvec2(0x2083Fu, 0x2108u),  // 33  7
    uvec2(0x7462Eu, 0x3A31u),  // 34  8
    uvec2(0x7C62Eu, 0x3041u),  // 35  9
    uvec2(0x00000u, 0x0000u),  // 36  space
    uvec2(0x00000u, 0x3180u),  // 37  period
    uvec2(0xF8000u, 0x0000u),  // 38  hyphen
    uvec2(0x00000u, 0x218Cu),  // 39  comma
    uvec2(0x03180u, 0x018Cu),  // 40  colon
    uvec2(0x20841u, 0x4108u),  // 41  slash
    uvec2(0xF9080u, 0x0084u),  // 42  plus
    uvec2(0x20B59u, 0x4D68u),  // 43  percent
    uvec2(0xFB880u, 0x008Eu)   // 44  diamond
);

// uv is 0..1 across one 5x7 cell. Returns 1 for a lit lamp, 0 for dark --
// the CALLER decides what dark looks like, because on this panel an unlit
// lamp is still faintly visible and that is most of the 70s in it.
float glyphBit(int gid, vec2 uv) {
    if (gid < 0 || gid >= GLYPH_COUNT) return 0.0;
    if (uv.x < 0.0 || uv.x >= 1.0 || uv.y < 0.0 || uv.y >= 1.0) return 0.0;
    int cx = int(uv.x * 5.0);
    int ry = 6 - int(uv.y * 7.0);          // row 0 is the TOP row
    uvec2 g = FONT[gid];
    uint bits = (ry < 4) ? (g.x >> uint(5 * ry)) : (g.y >> uint(5 * (ry - 4)));
    bits &= 31u;
    return float((bits >> uint(4 - cx)) & 1u);
}
`;
