#!/usr/bin/env python3
"""Emit boltrig/fleet/personas.py from the shipped character bundles.

WHY GENERATE RATHER THAN READ AT RUNTIME. The bundles live under
apps/worker/src/bundles, which is the WEB CLIENT's tree. The kernel ships as its
own container and has no reason to carry the worker's source; a runtime read
would either add that dependency or fail closed in production while passing
every test on a developer's checkout. Generating a module makes the persona
table an ordinary Python constant that travels with the kernel, and makes drift
between the two trees a gate failure rather than a silent difference in what a
character says.

WHY AN ID, NEVER PROSE, CROSSES THE WIRE. A client selects a character by id and
the server resolves it here. That is the whole security property: the set of
personas is fixed at build time, so a caller cannot supply persona text and
cannot reach a persona that was not shipped. An unrecognised id resolves to no
persona rather than raising, which is the same degrade-don't-throw rule the web
client's `characterFor` already follows for a body it cannot draw.

The persona carries NO AUTHORITY. It is prose appended below the governance
floor, and the grant check at the Dispatcher chokepoint has never read a word of
it. See tests/test_persona_layer.py, which hands the composer a persona trying
to cancel the cage and asserts the cage is still there and still first.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
BUNDLES = ROOT / "apps/worker/src/bundles"
OUT = ROOT / "boltrig/fleet/personas.py"

HEADER = '''"""Character personas, keyed by id.

GENERATED by scripts/gen_personas.py from apps/worker/src/bundles/*/character.json
-- do not hand-edit. Regenerate and commit; tests/test_chat_persona.py fails if this
file and the bundles disagree.

A persona is PROSE AND NOTHING ELSE. It shapes how an answer reads. It cannot
widen grants, reach a tool, or change routing: it is composed below the
governance floor in `prompt_stack`, and the Dispatcher that checks authority
never reads it.
"""

from __future__ import annotations

'''


def collect() -> dict[str, dict[str, str]]:
    personas: dict[str, dict[str, str]] = {}
    for path in sorted(BUNDLES.glob("*/character.json")):
        bundle = json.loads(path.read_text(encoding="utf-8"))
        prompts = bundle.get("prompts")
        if not isinstance(prompts, dict):
            # A character with no persona is expressible and stays absent here.
            # Familiar was that character until her constitution was written.
            continue
        system = (prompts.get("system") or "").strip()
        if not system:
            continue
        personas[bundle["id"]] = {
            "name": bundle.get("name", bundle["id"]),
            "system": system,
        }
    return personas


def render(personas: dict[str, dict[str, str]]) -> str:
    lines = [HEADER, "PERSONAS: dict[str, dict[str, str]] = {"]
    for cid, entry in personas.items():
        lines.append(f"    {json.dumps(cid)}: {{")
        lines.append(f"        \"name\": {json.dumps(entry['name'])},")
        lines.append(f"        \"system\": {json.dumps(entry['system'])},")
        lines.append("    },")
    lines += [
        "}",
        "",
        "",
        "def persona_for(character_id: str | None) -> str | None:",
        '    """The persona text for a character id, or None.',
        "",
        "    None for an unknown id rather than an exception: a character that is not",
        "    installed must cost the turn its voice and nothing else. The same rule the",
        "    web client applies to a body it cannot draw.",
        '    """',
        "    if not character_id:",
        "        return None",
        "    entry = PERSONAS.get(character_id.strip().lower())",
        "    return entry[\"system\"] if entry else None",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    text = render(collect())
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("STALE: boltrig/fleet/personas.py does not match the bundles.")
            print("Regenerate with `python scripts/gen_personas.py` and commit.")
            return 1
        print(f"personas: current ({len(collect())} characters)")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(collect())} characters)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
